#!/bin/bash
set -eu

function print_usage {
	echo "Usage: $(basename $0) <src> <dst> [options]"
	echo "	Options:"
	echo "		--arch [arch]: x86_64(default)|i386|aarch64|arm"
	echo "		-n|--dryrun: show the copy command that will be executed and exit"
	echo "		-h|--help: print this help message"
}

ARCH=x86_64
DRYRUN=0

SHORTOPTS="hn"
LONGOPTS="arch:,help,dryrun"

ARGS==`getopt -n "$(basename $0)" --options $SHORTOPTS --longoptions $LONGOPTS -- "$@"`

eval set -- "$ARGS"

while true;
do
	case "$1" in
		-h|--help)
			print_usage
			exit 0
			;;

		--arch)
			shift
			ARCH="$1"
			;;

		-n|--dryrun)
			DRYRUN=1
			;;

		--)
			shift
			break
			;;
	esac
	shift
done

if [ $# -lt 2 ]; then
	print_usage
	exit -1
fi

for i in $(seq $(($# - 1)))
do
	SRC+="$(echo $1 | sed s#^/*##) "
	shift
done

DST=$(realpath $1)

if [ $DRYRUN -eq 1 ]; then
	echo "cp -r $SRC $DST"
	exit 0
fi

# Information required by plumbing layer
IMG=$(dirname $(realpath $0))/images/qemu-image-$ARCH.img
MNT=$(dirname $(realpath $0))/mnt/$ARCH

# Make sure to cleanup on exit
trap "popd &> /dev/null && $(dirname $(realpath $0))/bin/umount_img.sh $MNT" EXIT

sudo mount -o loop $IMG $MNT

pushd $MNT &> /dev/null

set -x
cp -r $SRC $DST
set +x
