#!/bin/bash
set -eu

function print_usage {
	echo "Usage: $(basename $0) <src> <dst> [options]"
	echo "	Options:"
	echo "		--arch [arch]: x86_64(default)|i386|aarch64|arm"
	echo "		-h|--help: print this help message"
}

ARCH=x86_64

SHORTOPTS="h"
LONGOPTS="arch:,help"

ARGS==`getopt -n "$(basename $0)" --options $SHORTOPTS --longoptions $LONGOPTS -- "$@"`

eval set -- "$ARGS"

while true;
do
	case "$1" in
		-h|--help)
			print_usage
			exit 0
			;;

		--arch)
			shift
			ARCH="$1"
			;;

		--)
			shift
			break
			;;
	esac
	shift
done

if [ $# -lt 2 ]; then
	print_usage
	exit -1
fi

for i in $(seq $(($# - 1)))
do
	SRC+="$(realpath $1) "
	shift
done

DST=$(echo $1 | sed s#^/*##)

echo $SRC
echo $DST

# Information required by plumbing layer
IMG=$(dirname $(realpath $0))/images/qemu-image-$ARCH.img
MNT=$(dirname $(realpath $0))/mnt/$ARCH

# Make sure to cleanup on exit
trap "$(dirname $(realpath $0))/bin/umount_img.sh $MNT" EXIT

sudo mount -o loop $IMG $MNT

pushd $MNT &> /dev/null

set -x
cp -r $SRC $DST
set +x
popd &> /dev/null
